// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutpageDocumentDataSlicesSlice =
  | FooterSectionSlice
  | HeroV2Slice
  | StackedgallerySlice
  | TeamGallerySlice
  | DescriptionSlice
  | DiscoverSectionSlice;

/**
 * Content for AboutPage documents
 */
interface AboutpageDocumentData {
  /**
   * Slice Zone field in *AboutPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutpageDocumentDataSlicesSlice>;
}

/**
 * AboutPage document from Prismic
 *
 * - **API ID**: `aboutpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutpageDocumentData>,
    'aboutpage',
    Lang
  >;

type ArticlesDocumentDataSlicesSlice = ArticlesSlice;

/**
 * Content for Articles documents
 */
interface ArticlesDocumentData {
  /**
   * Slice Zone field in *Articles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticlesDocumentDataSlicesSlice>;
}

/**
 * Articles document from Prismic
 *
 * - **API ID**: `articles`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticlesDocumentData>,
    'articles',
    Lang
  >;

type ContactDocumentDataSlicesSlice = FooterSectionSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    'contact',
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | SectionSliceSlice
  | HeroSliceSlice
  | Section2Slice
  | FooterSectionSlice
  | DiscoverSectionSlice
  | GallerySlice
  | Section3Slice
  | Section4Slice;

/**
 * Content for HomeScreen documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *HomeScreen*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
}

/**
 * HomeScreen document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>;

type OurworkDocumentDataSlicesSlice =
  | OurworkSectionSlice
  | ArticlesSlice
  | HeroV2Slice;

/**
 * Content for our work documents
 */
interface OurworkDocumentData {
  /**
   * Slice Zone field in *our work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ourwork.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OurworkDocumentDataSlicesSlice>;
}

/**
 * our work document from Prismic
 *
 * - **API ID**: `ourwork`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OurworkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OurworkDocumentData>,
    'ourwork',
    Lang
  >;

type PageDocumentDataSlicesSlice = SectionSliceSlice | HeroSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * link field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

type SustainabilityDocumentDataSlicesSlice =
  | HeroV2Slice
  | DescriptionSlice
  | FooterSectionSlice
  | Section5Slice
  | MultiCarouseSlice;

/**
 * Content for sustainability documents
 */
interface SustainabilityDocumentData {
  /**
   * Slice Zone field in *sustainability*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sustainability.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SustainabilityDocumentDataSlicesSlice>;
}

/**
 * sustainability document from Prismic
 *
 * - **API ID**: `sustainability`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SustainabilityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SustainabilityDocumentData>,
    'sustainability',
    Lang
  >;

export type AllDocumentTypes =
  | AboutpageDocument
  | ArticlesDocument
  | ContactDocument
  | HomeDocument
  | OurworkDocument
  | PageDocument
  | SustainabilityDocument;

/**
 * Primary content in *Articles → Primary*
 */
export interface ArticlesSliceDefaultPrimary {
  /**
   * Article Image field in *Articles → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  article_image: prismic.ImageField<never>;

  /**
   * Article Date field in *Articles → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  article_date: prismic.DateField;

  /**
   * Article Title field in *Articles → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_title: prismic.TitleField;

  /**
   * Article Content field in *Articles → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_content: prismic.RichTextField;

  /**
   * Article Link field in *Articles → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article_link: prismic.LinkField;

  /**
   * Article Summary field in *Articles → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_summary
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_summary: prismic.RichTextField;

  /**
   * Article Category field in *Articles → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  article_category: prismic.SelectField<'Web3' | 'NFT' | 'Cryptocurrency'>;

  /**
   * Slug field in *Articles → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slug: prismic.TitleField;

  /**
   * Article Author field in *Articles → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_author
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_author: prismic.TitleField;

  /**
   * Article Read Time field in *Articles → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.primary.article_read_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_read_time: prismic.RichTextField;
}

/**
 * Primary content in *Articles → Items*
 */
export interface ArticlesSliceDefaultItem {
  /**
   * Title field in *Articles → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Desctiption field in *Articles → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.items[].desctiption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  desctiption: prismic.RichTextField;

  /**
   * Image field in *Articles → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Articles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Articles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ArticlesSliceDefaultPrimary>,
  Simplify<ArticlesSliceDefaultItem>
>;

/**
 * Slice variation for *Articles*
 */
type ArticlesSliceVariation = ArticlesSliceDefault;

/**
 * Articles Shared Slice
 *
 * - **API ID**: `articles`
 * - **Description**: Articles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesSlice = prismic.SharedSlice<
  'articles',
  ArticlesSliceVariation
>;

/**
 * Primary content in *Description → Primary*
 */
export interface DescriptionSliceDefaultPrimary {
  /**
   * Title field in *Description → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: description.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description1 field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: description.primary.description1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Subtitle field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Description2 field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.description2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * Description3 field in *Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.primary.description3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description3: prismic.RichTextField;
}

/**
 * Primary content in *Description → Items*
 */
export interface DescriptionSliceDefaultItem {
  /**
   * Description field in *Description → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Description Slice
 *
 * - **API ID**: `default`
 * - **Description**: Description
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DescriptionSliceDefaultPrimary>,
  Simplify<DescriptionSliceDefaultItem>
>;

/**
 * Slice variation for *Description*
 */
type DescriptionSliceVariation = DescriptionSliceDefault;

/**
 * Description Shared Slice
 *
 * - **API ID**: `description`
 * - **Description**: Description
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSlice = prismic.SharedSlice<
  'description',
  DescriptionSliceVariation
>;

/**
 * Primary content in *DiscoverSection → Primary*
 */
export interface DiscoverSectionSliceDefaultPrimary {
  /**
   * Title field in *DiscoverSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: discover_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *DiscoverSection → Items*
 */
export interface DiscoverSectionSliceDefaultItem {
  /**
   * icon field in *DiscoverSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: discover_section.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *DiscoverSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discover_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Content field in *DiscoverSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discover_section.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * More field in *DiscoverSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Coming soon
   * - **API ID Path**: discover_section.items[].more
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  more: prismic.LinkField;
}

/**
 * Default variation for DiscoverSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: DiscoverSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscoverSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DiscoverSectionSliceDefaultPrimary>,
  Simplify<DiscoverSectionSliceDefaultItem>
>;

/**
 * Slice variation for *DiscoverSection*
 */
type DiscoverSectionSliceVariation = DiscoverSectionSliceDefault;

/**
 * DiscoverSection Shared Slice
 *
 * - **API ID**: `discover_section`
 * - **Description**: DiscoverSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscoverSectionSlice = prismic.SharedSlice<
  'discover_section',
  DiscoverSectionSliceVariation
>;

/**
 * Primary content in *Footer → Primary*
 */
export interface FooterSectionSliceDefaultPrimary {
  /**
   * Title field in *Footer → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: footer_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * item1 field in *Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.item1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item1: prismic.RichTextField;

  /**
   * link1 field in *Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.itemlink1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  itemlink1: prismic.LinkField;

  /**
   * item2 field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.item2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item2: prismic.KeyTextField;

  /**
   * link2 field in *Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkField;

  /**
   * item3 field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.item3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item3: prismic.KeyTextField;

  /**
   * link3 field in *Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.link3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link3: prismic.LinkField;

  /**
   * item4 field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.item4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item4: prismic.KeyTextField;

  /**
   * link4 field in *Footer → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.link4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link4: prismic.LinkField;

  /**
   * Title2 field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Title3 field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.title3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title3: prismic.KeyTextField;

  /**
   * Title1 field in *Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * Subtitle field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Content field in *Footer → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: FooterSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSectionSliceVariation = FooterSectionSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer_section`
 * - **Description**: FooterSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSectionSlice = prismic.SharedSlice<
  'footer_section',
  FooterSectionSliceVariation
>;

/**
 * Primary content in *Gallery → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Title field in *Gallery → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: gallery.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Gallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: gallery.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * type field in *Gallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primary.type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Gallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * content field in *Gallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * link1 field in *Gallery → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkField;

  /**
   * link2 field in *Gallery → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkField;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  'gallery',
  GallerySliceVariation
>;

/**
 * Primary content in *GalleryRow → Primary*
 */
export interface GalleryRowSliceDefaultPrimary {
  /**
   * Title field in *GalleryRow → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: gallery_row.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *GalleryRow → Items*
 */
export interface GalleryRowSliceDefaultItem {
  /**
   * image field in *GalleryRow → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_row.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *GalleryRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_row.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *GalleryRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_row.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for GalleryRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: GalleryRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryRowSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GalleryRowSliceDefaultPrimary>,
  Simplify<GalleryRowSliceDefaultItem>
>;

/**
 * Slice variation for *GalleryRow*
 */
type GalleryRowSliceVariation = GalleryRowSliceDefault;

/**
 * GalleryRow Shared Slice
 *
 * - **API ID**: `gallery_row`
 * - **Description**: GalleryRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryRowSlice = prismic.SharedSlice<
  'gallery_row',
  GalleryRowSliceVariation
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Caption1 field in *HeroSlice → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: hero_slice.primary.caption1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption1: prismic.TitleField;

  /**
   * Caption2 field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: hero_slice.primary.caption2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption2: prismic.RichTextField;

  /**
   * Caption3 field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.caption3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption3: prismic.RichTextField;

  /**
   * content field in *HeroSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  'hero_slice',
  HeroSliceSliceVariation
>;

/**
 * Primary content in *HeroV2 → Primary*
 */
export interface HeroV2SliceDefaultPrimary {
  /**
   * Title field in *HeroV2 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: hero_v2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeroV2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: hero_v2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * backgroung field in *HeroV2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_v2.primary.backgroung
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroung: prismic.ImageField<never>;
}

/**
 * Default variation for HeroV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroV2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroV2SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroV2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroV2*
 */
type HeroV2SliceVariation = HeroV2SliceDefault;

/**
 * HeroV2 Shared Slice
 *
 * - **API ID**: `hero_v2`
 * - **Description**: HeroV2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroV2Slice = prismic.SharedSlice<'hero_v2', HeroV2SliceVariation>;

/**
 * Primary content in *MultiCarouse → Primary*
 */
export interface MultiCarouseSliceDefaultPrimary {
  /**
   * Title field in *MultiCarouse → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_carouse.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *MultiCarouse → Items*
 */
export interface MultiCarouseSliceDefaultItem {
  /**
   * image field in *MultiCarouse → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_carouse.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *MultiCarouse → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_carouse.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * desctiption field in *MultiCarouse → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_carouse.items[].desctiption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  desctiption: prismic.RichTextField;

  /**
   * link field in *MultiCarouse → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_carouse.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for MultiCarouse Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultiCarouseSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MultiCarouseSliceDefaultPrimary>,
  Simplify<MultiCarouseSliceDefaultItem>
>;

/**
 * Slice variation for *MultiCarouse*
 */
type MultiCarouseSliceVariation = MultiCarouseSliceDefault;

/**
 * MultiCarouse Shared Slice
 *
 * - **API ID**: `multi_carouse`
 * - **Description**: MultiCarouse
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultiCarouseSlice = prismic.SharedSlice<
  'multi_carouse',
  MultiCarouseSliceVariation
>;

/**
 * Primary content in *OurworkSection → Primary*
 */
export interface OurworkSectionSliceDefaultPrimary {
  /**
   * Title field in *OurworkSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: ourwork_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *OurworkSection → Items*
 */
export interface OurworkSectionSliceDefaultItem {
  /**
   * Project Image field in *OurworkSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ourwork_section.items[].project_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Project title field in *OurworkSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourwork_section.items[].project_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_title: prismic.RichTextField;

  /**
   * Project description field in *OurworkSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourwork_section.items[].project_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField;

  /**
   * Project link field in *OurworkSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ourwork_section.items[].project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;
}

/**
 * Default variation for OurworkSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: OurworkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurworkSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<OurworkSectionSliceDefaultPrimary>,
  Simplify<OurworkSectionSliceDefaultItem>
>;

/**
 * Slice variation for *OurworkSection*
 */
type OurworkSectionSliceVariation = OurworkSectionSliceDefault;

/**
 * OurworkSection Shared Slice
 *
 * - **API ID**: `ourwork_section`
 * - **Description**: OurworkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurworkSectionSlice = prismic.SharedSlice<
  'ourwork_section',
  OurworkSectionSliceVariation
>;

/**
 * Primary content in *Section2 → Items*
 */
export interface Section2SliceDefaultItem {
  /**
   * Title field in *Section2 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Section2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Section2 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Section2 → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Section2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section2SliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<Section2SliceDefaultItem>
>;

/**
 * Slice variation for *Section2*
 */
type Section2SliceVariation = Section2SliceDefault;

/**
 * Section2 Shared Slice
 *
 * - **API ID**: `section2`
 * - **Description**: Section2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section2Slice = prismic.SharedSlice<
  'section2',
  Section2SliceVariation
>;

/**
 * Primary content in *Section3 → Primary*
 */
export interface Section3SliceDefaultPrimary {
  /**
   * Title field in *Section3 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: section3.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Section3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: section3.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Section3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section3SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Section3SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section3*
 */
type Section3SliceVariation = Section3SliceDefault;

/**
 * Section3 Shared Slice
 *
 * - **API ID**: `section3`
 * - **Description**: Section3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section3Slice = prismic.SharedSlice<
  'section3',
  Section3SliceVariation
>;

/**
 * Primary content in *Section4 → Primary*
 */
export interface Section4SliceDefaultPrimary {
  /**
   * Title field in *Section4 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: section4.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * image field in *Section4 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section4.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Section4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section4
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section4SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Section4SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section4*
 */
type Section4SliceVariation = Section4SliceDefault;

/**
 * Section4 Shared Slice
 *
 * - **API ID**: `section4`
 * - **Description**: Section4
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section4Slice = prismic.SharedSlice<
  'section4',
  Section4SliceVariation
>;

/**
 * Primary content in *Section5 → Primary*
 */
export interface Section5SliceDefaultPrimary {
  /**
   * Title field in *Section5 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: section5.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Title2 field in *Section5 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: section5.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * Title3 field in *Section5 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section5.primary.title3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title3: prismic.RichTextField;

  /**
   * Subtitle field in *Section5 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section5.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Comment field in *Section5 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section5.primary.comment
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  comment: prismic.RichTextField;
}

/**
 * Primary content in *Section5 → Items*
 */
export interface Section5SliceDefaultItem {
  /**
   * Icon field in *Section5 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section5.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Section5 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section5.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Section5 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section5.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Section5 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section5
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section5SliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<Section5SliceDefaultPrimary>,
  Simplify<Section5SliceDefaultItem>
>;

/**
 * Slice variation for *Section5*
 */
type Section5SliceVariation = Section5SliceDefault;

/**
 * Section5 Shared Slice
 *
 * - **API ID**: `section5`
 * - **Description**: Section5
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Section5Slice = prismic.SharedSlice<
  'section5',
  Section5SliceVariation
>;

/**
 * Primary content in *Section1 → Primary*
 */
export interface SectionSliceSliceDefaultPrimary {
  /**
   * Title field in *Section1 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: section_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Section1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: section_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * content field in *Section1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * description field in *Section1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Section1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: SectionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SectionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section1*
 */
type SectionSliceSliceVariation = SectionSliceSliceDefault;

/**
 * Section1 Shared Slice
 *
 * - **API ID**: `section_slice`
 * - **Description**: SectionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionSliceSlice = prismic.SharedSlice<
  'section_slice',
  SectionSliceSliceVariation
>;

/**
 * Primary content in *Stackedgallery → Primary*
 */
export interface StackedgallerySliceDefaultPrimary {
  /**
   * Title field in *Stackedgallery → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: stackedgallery.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Stackedgallery → Items*
 */
export interface StackedgallerySliceDefaultItem {
  /**
   * image field in *Stackedgallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stackedgallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Stackedgallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stackedgallery.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Stackedgallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stackedgallery.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Stackedgallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Stackedgallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackedgallerySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<StackedgallerySliceDefaultPrimary>,
  Simplify<StackedgallerySliceDefaultItem>
>;

/**
 * Slice variation for *Stackedgallery*
 */
type StackedgallerySliceVariation = StackedgallerySliceDefault;

/**
 * Stackedgallery Shared Slice
 *
 * - **API ID**: `stackedgallery`
 * - **Description**: Stackedgallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackedgallerySlice = prismic.SharedSlice<
  'stackedgallery',
  StackedgallerySliceVariation
>;

/**
 * Primary content in *TeamGallery → Primary*
 */
export interface TeamGallerySliceDefaultPrimary {
  /**
   * Title field in *TeamGallery → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: team_gallery.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *TeamGallery → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: team_gallery.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *TeamGallery → Items*
 */
export interface TeamGallerySliceDefaultItem {
  /**
   * title field in *TeamGallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_gallery.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *TeamGallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_gallery.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * image field in *TeamGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *TeamGallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_gallery.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TeamGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: TeamGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamGallerySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TeamGallerySliceDefaultPrimary>,
  Simplify<TeamGallerySliceDefaultItem>
>;

/**
 * Slice variation for *TeamGallery*
 */
type TeamGallerySliceVariation = TeamGallerySliceDefault;

/**
 * TeamGallery Shared Slice
 *
 * - **API ID**: `team_gallery`
 * - **Description**: TeamGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamGallerySlice = prismic.SharedSlice<
  'team_gallery',
  TeamGallerySliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutpageDocument,
      AboutpageDocumentData,
      ArticlesDocument,
      ArticlesDocumentData,
      ContactDocument,
      ContactDocumentData,
      HomeDocument,
      HomeDocumentData,
      OurworkDocument,
      OurworkDocumentData,
      PageDocument,
      PageDocumentData,
      SustainabilityDocument,
      SustainabilityDocumentData,
      AllDocumentTypes,
      ArticlesSlice,
      ArticlesSliceVariation,
      ArticlesSliceDefault,
      DescriptionSlice,
      DescriptionSliceVariation,
      DescriptionSliceDefault,
      DiscoverSectionSlice,
      DiscoverSectionSliceVariation,
      DiscoverSectionSliceDefault,
      FooterSectionSlice,
      FooterSectionSliceVariation,
      FooterSectionSliceDefault,
      GallerySlice,
      GallerySliceVariation,
      GallerySliceDefault,
      GalleryRowSlice,
      GalleryRowSliceVariation,
      GalleryRowSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      HeroV2Slice,
      HeroV2SliceVariation,
      HeroV2SliceDefault,
      MultiCarouseSlice,
      MultiCarouseSliceVariation,
      MultiCarouseSliceDefault,
      OurworkSectionSlice,
      OurworkSectionSliceVariation,
      OurworkSectionSliceDefault,
      Section2Slice,
      Section2SliceVariation,
      Section2SliceDefault,
      Section3Slice,
      Section3SliceVariation,
      Section3SliceDefault,
      Section4Slice,
      Section4SliceVariation,
      Section4SliceDefault,
      Section5Slice,
      Section5SliceVariation,
      Section5SliceDefault,
      SectionSliceSlice,
      SectionSliceSliceVariation,
      SectionSliceSliceDefault,
      StackedgallerySlice,
      StackedgallerySliceVariation,
      StackedgallerySliceDefault,
      TeamGallerySlice,
      TeamGallerySliceVariation,
      TeamGallerySliceDefault,
    };
  }
}
