// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  articles: dynamic(() => import('./Articles')),
  description: dynamic(() => import('./Description')),
  discover_section: dynamic(() => import('./DiscoverSection')),
  footer_section: dynamic(() => import('./Footer')),
  gallery: dynamic(() => import('./Gallery')),
  gallery_row: dynamic(() => import('./GalleryRow')),
  hero_slice: dynamic(() => import('./HeroSlice')),
  hero_v2: dynamic(() => import('./HeroV2')),
  multi_carouse: dynamic(() => import('./MultiCarouse')),
  ourwork_section: dynamic(() => import('./OurworkSection')),
  section2: dynamic(() => import('./Section2')),
  section3: dynamic(() => import('./Section3')),
  section4: dynamic(() => import('./Section4')),
  section5: dynamic(() => import('./Section5')),
  section_slice: dynamic(() => import('./Section1')),
  stackedgallery: dynamic(() => import('./Stackedgallery')),
  team_gallery: dynamic(() => import('./TeamGallery')),
};
